django_news_url_params/django_news/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^edit/', include('edit.urls', namespace='edit')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^date/today', views.today),
    url(r'^date-by-weekday/(?P<weekday>[a-zA-Z]+)', views.date_by_weekday),
    url(r'^weekday-by-date/'
        '(?P<date>date\(\d{2}-\d{2}-\d{4}\))', views.weekday_by_date),
    url(r'^date-range/(?P<date_begin>date-begin\(\d{2}-\d{2}-\d{4}\))'
        '/(?P<date_end>date-end\(\d{2}-\d{2}-\d{4}\))', views.date_range),
    url(r'^payment/ndfl/(?P<salary>\d+)', views.payment_ndfl),
    url(r'^payment/pension/(?P<salary>\d+)', views.payment_pension),
    url(r'^payment/other-pay/(?P<salary>\d+)', views.payment_other_pay),
    url(r'^$', views.IndexTemplateView.as_view(), name='index'),
    url(r'^news$', views.NewsTemplateView.as_view(), name='news'),
    url(ur'^news/(?P<slug>.+)$',
        views.NewsDetailView.as_view(), name='news_item'),
    url(r'^news/category/by-viewed$',
        views.NewsByViewedListView.as_view(), name='news_by_viewed'),
    url(r'^news/category/by-latest$',
        views.NewsByLatestListView.as_view(), name='news_by_latest'),
    url(r'^news/category/by-comments$',
        views.NewsByCommentsListView.as_view(), name='news_by_comments'),
    url(r'^registration',
        views.RegistrationFormView.as_view(), name='registration'),
    url(r'^login', views.LoginFormView.as_view(), name='login'),
    url(r'^logout', views.LogoutView.as_view(), name='logout'),
    url(r'^personal$', views.PersonalListView.as_view(), name='personal'),
    url(r'^about$',
        TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^jquery_tasks$',
        TemplateView.as_view(template_name='jquery_tasks.html'),
        name='jquery_tasks'),
    url(r'^single-page',
        views.SinglePageListView.as_view(), name='single_page'),
    url(r'^get-news/$',
        views.SinglePageJSONNewsListView.as_view(), name='get_news'),
    url(r'^get-news/(?P<pk>\d+)/text',
        views.SinglePageJSONNewsDetailView.as_view(), name='get_news_text'),
    url(r'^add-bookmark',
        views.SinglePageJSONBookmarkCreateView.as_view(), name='add_bookmark'),
    url(r'^get-bookmarks/$',
        views.SinglePageJSONBookmarksListView.as_view(), name='get_bookmarks'),
    url(r'^is-bookmark-exists/$',
        views.SinglePageJSONBookmarkExistsDetailView.as_view(),
        name='is_bookmark_exists'),
    url(r'^rm-bookmark/by-news/(?P<news>\d+)$',
        views.SinglePageJSONBookmarkDeleteView.as_view(), name='rm_bookmarks'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_news_url_params/edit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^personal$', views.PersonalListView.as_view(), name='personal'),
    url(r'^add-news$', views.NewsCreateView.as_view(), name='add_news'),
    url(r'^add-news/(?P<pk>.+)$',
        views.NewsUpdateView.as_view(), name='add_news'),
]

django_news_url_params/django_news/models.py
# -*- coding: utf-8 -*-
from django.db import models
from tinymce.models import HTMLField

import re
from datetime import date


class News(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100)
    slug = models.SlugField(verbose_name='slug')
    text = HTMLField(verbose_name='Текст')
    created = models.DateField(verbose_name='Дата создания')
    changed = models.DateField(verbose_name='Дата изменения')
    image = models.ImageField(verbose_name='Изображение', blank=True)
    viewed = models.IntegerField(
        verbose_name='Количество просмотров', blank=True, default=0)
    user = models.ForeignKey('auth.User', blank=True, null=True)
    editor = models.ForeignKey('edit.Editor', blank=True, null=True)

    @property
    def text_short(self):
        from django.utils.html import strip_tags
        count = 30
        stripped = strip_tags(self.text).strip()
        return ' '.join(re.split('\s', stripped)[:count+1]) + '...'

    @property
    def comment_count(self):
        return self.comment_set.count()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('news_item', kwargs={'slug': self.slug})

    def __str__(self):
        return 'News: %s' % self.name


class User(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=255)
    lastname = models.CharField(
        verbose_name='Фамилия', max_length=255, null=True)
    registration_date = models.DateField(
        verbose_name='Дата регистрации', default=date.today)

    def __str__(self):
        return 'User: %s' % self.name


class Comment(models.Model):
    comment = models.TextField(verbose_name='Комментарий')
    date = models.DateField(
        verbose_name='Дата публикации', null=True, auto_now_add=True)
    user = models.ForeignKey('auth.User')
    news = models.ForeignKey('News')
    communication = models.CharField(
        verbose_name='Способ связи', max_length=255, null=True)

    def __str__(self):
        return 'Comment by %s: %s' % (self.user.username, self.comment[:25])


class Bookmark(models.Model):
    user = models.ForeignKey('auth.User')
    news = models.ForeignKey('News')

    class Meta:
        unique_together = ('user', 'news')

django_news_url_params/edit/models.py
from __future__ import unicode_literals

from django.db import models


class Editor(models.Model):
    user = models.OneToOneField('auth.User')

    def __str__(self):
        return 'Editor: %s' % self.user.username

django_news_url_params/edit/forms.py
from django import forms

from django_news.models import News

from datetime import datetime


class NewsModelForm(forms.ModelForm):
    def __init__(self, editor=None, user=None, *args, **kwargs):
        if user is not None and editor is not None:
            self.editor = editor
            self.user = user
        super(NewsModelForm, self).__init__(*args, **kwargs)

    class Meta:
        model = News
        fields = ('name', 'text')

    def save(self):
        news = super(NewsModelForm, self).save(commit=False)
        news.slug = self.cleaned_data.get('name').replace(' ', '-')
        news.created = datetime.now()
        news.changed = datetime.now()
        news.user = self.user
        news.editor = self.editor
        news.save()
        return news

django_news_url_params/edit/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse_lazy

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django_news.models import News
from edit.models import Editor

from .forms import NewsModelForm


def is_user_editor(user):
    try:
        Editor.objects.get(user=user)
    except Editor.DoesNotExist:
        return False
    return True


class PersonalListView(LoginRequiredMixin, ListView):
    login_url = '/login'
    template_name = u'edit/personal.html'
    context_object_name = 'news_list'

    def get_queryset(self):
        editor = Editor.objects.get(user=self.request.user)
        news_list = News.objects.filter(editor=editor)
        paginator = Paginator(news_list, 5)
        page = self.request.GET.get('page')
        try:
            news = paginator.page(page)
        except PageNotAnInteger:
            news = paginator.page(1)
        except EmptyPage:
            news = paginator.page(paginator.num_pages)
        return news

    def get_context_data(self, **kwargs):
        context = super(PersonalListView, self).get_context_data(**kwargs)
        context.update({
            'next_for_logout': True,
        })
        return context


class NewsCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    login_url = '/login'
    raise_exception = True
    model = News
    form_class = NewsModelForm
    template_name = u'edit/add_news.html'
    success_url = reverse_lazy('edit:personal')

    def test_func(self):
        return is_user_editor(self.request.user)

    def get_form_kwargs(self):
        kwargs = super(NewsCreateView, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user,
            'editor': self.request.user.editor,
        })
        return kwargs


class NewsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = '/login'
    raise_exception = True
    model = News
    form_class = NewsModelForm
    template_name = u'edit/add_news.html'
    success_url = reverse_lazy('edit:personal')

    def test_func(self):
        return is_user_editor(self.request.user)

    def get_form_kwargs(self):
        kwargs = super(NewsUpdateView, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user,
            'editor': self.request.user.editor,
        })
        return kwargs

django_news_url_params/edit/templates/edit/add_news.html
{% extends 'index_base.html' %}
{% load staticfiles %}

{% block title %}
    Добавление новости
{% endblock %}

{% block html_header %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    {{ form.media }}
{% endblock %}

{% block header %}
    {% include 'header_content.html' %}
{% endblock %}

{% block content__body %}
    {% include 'edit/add_news__content__body.html' %}
{% endblock %}

django_news_url_params/edit/templates/edit/add_news__content__body.html
<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.name.label_tag }}
    <p><input type="text" required name="{{ form.name.name }}" value="{{ form.name.value|default_if_none:'' }}"></p>
    {{ form.name.errors }}
    {{ form.text.label_tag }}
    {{ form.text }}
    {{ form.text.errors }}
    <button type="submit">Сохранить</button>
</form>

django_news_url_params/edit/templates/edit/index.html
Hello!

django_news_url_params/edit/templates/edit/personal.html
{% extends 'index_base.html' %}

{% block title %}
    Кабинет редактора
{% endblock %}

{% block header %}
    {% include 'header_content.html' %}
{% endblock %}

{% block content__body %}
    {% include 'edit/personal__content__body.html' %}
{% endblock %}

django_news_url_params/edit/templates/edit/personal__content__body.html
<div class="personal">
    {% if request.user.is_authenticated %}
        <a href="{% url 'edit:add_news' %}">Добавить новость</a>
        <p>Cсылки на все созданные редактором новости:</p>
        <ul>
            {% for news in news_list %}
                <li>
                    <a href="{{ news.get_absolute_url }}">{{ news.name }}</a> =&gt; <a class="a-color" href="{% url 'edit:add_news' news.id %}">Редактировать</a>
                </li>
            {% endfor %}
        </ul>
        <div class="pagination">
            <span class="step-links">
                {% if news_list.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}">&lt;</a>
                {% endif %}

                <span class="current">
                    Страница {{ news_list.number }} из {{ news_list.paginator.num_pages }}.
                </span>

                {% if news_list.has_next %}
                    <a href="?page={{ news_list.next_page_number }}">&gt;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</div>